name: Laravel CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, xml, tokenizer  # Extensiones básicas sin DB
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Prepare environment (No DB)
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "APP_ENV=testing" >> .env

    - name: Run tests (Solo pruebas sin DB)
      run: php artisan test