name: Laravel CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, fileinfo, openssl, pdo, sqlite, tokenizer, xml, gd
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Prepare environment
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=:memory:" >> .env
        touch database/database.sqlite

    - name: Run tests
      run: |
        php artisan migrate:fresh --env=testing
        php artisan test